### ISSUE TITLE
No support for listing keys [JIRA: CLIENTS-921]

### ISSUE THREAD

**Issue by heylarson** [basho/riak-php-client#124]
I need to be able to list the keys in a bucket similar to the HTTP API examples:
`GET /buckets/bucket/keys?keys=true    # List all keys`

But have not found any support.  The closest I have found is this reference:
\Basho\Riak\Api\Http::buildPath(): line 204:
`case 'Basho\Riak\Command\Bucket\Keys':`

However, it doesn't appear that this class was actually implemented.

**Comment by christophermancini** [comment]
Hi @heylarson, at the time of initial redevelopment of the PHP client we decided that since the list keys operation is a very expensive operation for Riak and can be challenging to consume over HTTP (lack of pagination), that we did not implement it. Also, we have recently been focusing on addressing technical debt and improving Riak performance across the board which might lead to better list keys performance.

In the mean time, can I ask what your use case is? Maybe I can offer an alternate solution that will meet your needs without requiring additional changes to the client.

**Comment by heylarson** [comment]
Hey Chris,
Great to hear all the progress you're making on the library! The necessity for this functionality stems from a unit testing perspective. In between my integration unit tests, I like to clear any data from the previous test, which is where I found this function to be helpful. I agree with you in that this function could be expensive when used with larger data sets.  For my workaround, I have used the guzzle library to interact with the http api to remove buckets and keys between unit  tests, and works fine.  Thank you for getting back to me.  I'm open for other solutions of course.

**Comment by christophermancini** [comment]
@heylarson sorry for the delay. So, for this client, I handle cleanup of test data a few different ways.

* Use the default bucket type as it does not allow siblings, which only works if the functionality you are testing doesn't require siblings and conflict resolution
* Use PHPUnits setUpBeforeClass() and tearDownAfterClass() functions to setup / cleanup the values you need to stay consistent between tests within a TestCase:
  * choose bucket / key names to use for testing based on a unique value (timestamps are useful)
  * check for the existence of data you want to use and delete it if found
  * fill a bucket / key with initial data that you expect within the tests
* You can wipe the Riak ring data directory (i can provide info on how to do that)
* Run everything within a VM that you can trash and rebuild
* Use delete_immediate = true within advanced.config to avoid having Tombstones cause anomalies in tests

**Comment by christophermancini** [comment]
I am going to close this issue for now, if you need more help feel free to reopen this issue.
