### ISSUE TITLE
Header data should be included in ObjectResponse [JIRA: CLIENTS-944]

### ISSUE THREAD

**Issue by heylarson** [basho/riak-php-client#127]
It would be beneficial for the Basho\Riak\Command\Object\Response class to have a property for the header data that can be publicly accessible.

The header data contains valuable information that would be beneficial for the developer.

**Comment by christophermancini** [comment]
Hi @heylarson, may I ask which headers specifically you are interested in? I attempted to make sure the most commonly accessed headers as well as meta data headers were converted and stored within the Basho\Riak\Object class.

I can't attach them to the Response class because this library supports both the Riak HTTP and PB interfaces. Protocol Buffers does not use headers and could potentially cause a confusing user experience for PB users if they were accessible on the Response class.

Alternatively if there are headers you want to access that are not currently accessible, you can access them via the API bridge class Basho\Riak\Api\Http via `$riak->getApi()->getResponseHeaders()`.

**Comment by heylarson** [comment]
Thanks (again) for the response!  I have a requirement to determine the last time an object had been modified, which led me to reference the Last-Modified header from the Object response. Your implementation makes more sense now that you've mentioned the library accommodates both protocols.

I will try your solution today.  Thank you.
