### ISSUE TITLE
PHP7 soft reserved keywords "object" [JIRA: CLIENTS-1009]

### ISSUE THREAD

**Issue by basvandorst** [basho/riak-php-client#138]
**File:**
`src/Riak/Object.php`

**Message:**
Name "object" that is reserved for future use (does not cause an error in PHP 7) used as a use statement alias `Riak\Object`

*More information*
[List of other reserved words](http://php.net/manual/en/reserved.other-reserved-words.php)
[Doctrine cache issue](https://github.com/doctrine/cache/issues/179)

**Comment by christophermancini** [comment]
So, after reviewing https://github.com/doctrine/cache/issues/179 in more detail, the issue you are reporting requires a change to https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/RiakCache.php#L25 which is not managed by this repository. However, I am glad you posted the issue here because a few places in our code base needed to be updated. I have made those changes in #139 and they will go out in our next release of PHP.

Thanks!
