### ISSUE TITLE
Comparison to php-riak/riak-client [JIRA: CLIENTS-209]

### ISSUE THREAD

**Issue by pavelsmolka** [basho/riak-php-client#88]
There is another Riak PHP client, which I believe most of PHP devs working with Riak are aware of (That's different from the C-based library, which lives in the same GitHub namespace):

https://github.com/php-riak/riak-client

It seems to be under an active development as well, and I can see it also supports protobuf. Without extensively testing both and diving into the code, would you be able to provide a brief comparison of these two libraries?

**Comment by MarcoDeBortoli** [comment]
@pavelsmolka it's hard to tell what the differences are or will be, the only thing that I can tell you is that it's very new as also mentioned by the guy and likely born after this misunderstanding

https://github.com/basho/riak-php-client/pull/86

**Comment by christophermancini** [comment]
Hey Pavel, thanks for posting your question. Currently, the stable version of this client library was written to support version 1.4.* of Riak. I have been actively developing a complete rewrite which can be seen in the 2.0.x branch for the last few months and hope to be able to provide a public beta release by the end of this month.

Where they differ: Fabio worked very hard to get a stable client library compatible with 2.* features. He used the officially supported Java client for Riak as inspiration for his design. I have not tested it myself, but from my review a while back, it appeared that he was well on his way to completing a very feature rich and powerful client.

For the rewrite of this library, our goals are to keep it extremely simple, lightweight and extensible with a low amount of dependencies. We want to keep the barriers of entry for users of the library and contributors to be very low. When Fabio offered his work to us for the officially supported PHP client, we felt that his work was not inline with these goals, which is why we declined and encouraged him to make his client available to the community.

Though our 2.x client will not ship with support for PB, we intend to make it easy enough for you to add support yourself by extending the API bridge classes that use PB instead of HTTP to communicate with Riak. My goal is to also provide an tutorial on how you would go about doing so.

**Comment by Basho-JIRA** [comment]
Closing as the related GitHub issue was Closed. 

***[posted via JIRA by Derek Somogyi]***

**Comment by FabioBatSilva** [comment]
BTW
I wrote a simple [benchmark](https://github.com/FabioBatSilva/riak-clients-performance-comparison) to compare the [c-extension](https://github.com/php-riak/php_riak),  [basho-client](https://github.com/basho/riak-php-client) and the new [2.0 client](https://github.com/php-riak/riak-client) that I'm about to release.

**Comment by Basho-JIRA** [comment]
[~cmancini] See the comments above. 

***[posted via JIRA by Derek Somogyi]***
